
#Common settings that will be synced from server to client.
[General]
	#Enables or disables blocks being launched from explosions.
	#If false, explosions will still destroy blocks but won't create falling block entities.
	enableFallingBlocks = true
	#Enables or disables the destruction of blocks, creating craters.
	#If false, explosions will still cause visual and sound effects, but won't break blocks.
	enableCraterDestruction = true
	#Enables or disables glass being shattered by the explosion's shockwave.
	enableGlassBreaking = true
	#Enables or disables the flickering effect on Redstone Lamps near explosions.
	enableLampFlicker = true

#
#Fine-tuning for the glass breaking effect. High values can impact performance.
["Glass Breaking"]
	#The interval in game ticks between each glass breaking cycle.
	#1 tick = 0.05 seconds. Lower values make the effect smoother but use more server resources.
	#Default: 1
	#Range: 1 ~ 20
	glassBreakingIntervalTicks = 1
	#The maximum number of glass blocks that can be broken in a single processing cycle.
	#This prevents server lag from massive explosions. Higher values can handle large glass structures better but may cause spikes.
	#Default: 70
	#Range: 10 ~ 500
	glassBlocksPerCycle = 70
	#The base number of rays used to detect glass for a minimal power explosion.
	#More rays increase precision and the chance to hit small windows, but increase performance cost.
	#Default: 1000
	#Range: 500 ~ 10000
	glassBreakingBaseRayCount = 1000
	#How many additional rays are added per point of explosion power.
	#This makes powerful explosions more accurate at a distance.
	#Default: 140. A power 100 explosion will have 1000 + 100*140 = 15000 rays.
	#Range: 50 ~ 500
	glassBreakingPowerRayMultiplier = 140

#
#Crater Customization
["Crater Settings"]
	#Multiplier for the radius of the explosion crater.
	#Affects both crater size and the number of generated particles.
	#1.0 = default size.
	#Range: 0.1 ~ 50.0
	craterSizeMultiplier = 1.0
	#For explosions with power 40+, this controls the shape of the crater.
	#Determines the size of the solid 'core' relative to the total radius.
	#0.1 = very ray-like, 0.95 = almost a perfect sphere.
	#Default: 0.7 (70%)
	#Range: 0.1 ~ 0.95
	craterCoreRatio = 0.7

#
#Redstone Lamp Flickering
["Lamp Flickering"]
	#The radius around the player in which to search for lamps to flicker.
	#Warning: High values on servers with many players and lamps can cause lag.
	#Range: 1 ~ 100
	lampFlickerSearchRadius = 50

#Settings for the ambient explosion system, creating a 'battlefield' atmosphere.
[Ambient]
	#Globally enables or disables the ambient explosion sound system.
	enableAmbientExplosions = false
	#Minimum time in ticks between ambient explosion events (20 ticks = 1 second).
	#Range: 100 ~ 72000
	minTimeBetweenExplosions = 1200
	#Maximum time in ticks between ambient explosion events.
	#Range: 200 ~ 72000
	maxTimeBetweenExplosions = 6000
	#Minimum distance in blocks from the player where an ambient sound can originate.
	#Range: 100 ~ 10000
	minExplosionDistance = 501
	#Maximum distance in blocks from the player where an ambient sound can originate.
	#Range: 200 ~ 10000
	maxExplosionDistance = 5001
	#The maximum power a random 'Cataclysm' tier explosion can have.
	#Range: 40.0 ~ 200.0
	maxAmbientExplosionPower = 80.0

	#
	#Configuration for different ambient event scenarios.
	#The chance for a scenario is (its_weight / sum_of_all_scenario_weights).
	[Ambient.Scenarios]
		#Weight for a standard, single explosion event.
		#Range: 0 ~ 1000
		singleExplosionWeight = 70
		#Weight for a 'Chain Reaction' event (a series of increasingly powerful explosions).
		#Range: 0 ~ 1000
		chainReactionWeight = 15
		#Weight for an 'Artillery Shelling' event (a quiet shot followed by a delayed, loud impact).
		#Range: 0 ~ 1000
		shellingWeight = 15

		#
		#Settings for the 'Chain Reaction' scenario.
		[Ambient.Scenarios.ChainReaction]
			#Range: 2 ~ 20
			minChainReactionShots = 3
			#Range: 2 ~ 20
			maxChainReactionShots = 7
			#Range: 5 ~ 200
			minTimeBetweenChainShots = 10
			#Range: 10 ~ 400
			maxTimeBetweenChainShots = 40

		#
		#Settings for the 'Artillery Shelling' scenario.
		[Ambient.Scenarios.Shelling]
			#Minimum delay in ticks between the 'shot' sound and the 'impact' sound (20 ticks = 1s).
			#Range: 20 ~ 400
			minShellingDelay = 40
			#Maximum delay in ticks between the 'shot' and 'impact' sounds.
			#Range: 20 ~ 400
			maxShellingDelay = 140

	#
	#Weighted chances for explosion power tiers (for single and shelling events).
	#The chance for a tier is (its_weight / sum_of_all_weights). Set a weight to 0 to disable that tier.
	[Ambient.Power_Tiers_Weight]
		#Weight for 'Background Noise' (Power 1-4)
		#Range: 0 ~ 1000
		tier1_weight = 50
		#Weight for 'Local Skirmish' (Power 5-15)
		#Range: 0 ~ 1000
		tier2_weight = 25
		#Weight for 'Serious Battle' (Power 16-40)
		#Range: 0 ~ 1000
		tier3_weight = 15
		#Weight for 'Epicenter' (Power 41-80)
		#Range: 0 ~ 1000
		tier4_weight = 8
		#Weight for 'Cataclysm' (Power 81+)
		#Range: 0 ~ 1000
		tier5_weight = 2

	#
	#Enable or disable specific types of ambient sound environments.
	[Ambient.Sound_Types]
		#Surface: A clear explosion sound in an open area.
		enableSurfaceSounds = true
		#Cave: A loud, reverberating sound when both player and explosion are in a cave.
		enableCaveSounds = true
		#If enabled, an ambient cave explosion will cause a visual dust effect to fall from the ceiling.
		enableAmbientCaveDust = true

